module.exports = {
  YOUTUBE_API_KEY: '',
  TWITTER_CONSUMER_KEY: '',
  TWITTER_CONSUMER_SECRET: '',
  HASHID_SALT: '',
  EXPRESS_SESSION_SECRET: '',
  ALGOLIA_APP_ID: '',
  ALGOLIA_PUBLIC_API_KEY: '',
  ALGOLIA_SECRET_ADMIN_KEY: '',
};
